name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "DOCKER_IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
        run: |
          # Install AWS Elastic Beanstalk CLI
          pip install awsebcli --upgrade

          # Initialize Elastic Beanstalk CLI
          echo $DOCKER_IMAGE
          echo $AWS_REGION
          echo $EB_APPLICATION_NAME
          echo $EB_ENVIRONMENT_NAME
          eb init -p docker $EB_APPLICATION_NAME --region $AWS_REGION

          # Set the environment to use
          eb use $EB_ENVIRONMENT_NAME

          # Create Dockerrun.aws.json file
          echo '{
            "AWSEBDockerrunVersion": "2",
            "Image": {
              "Name": "'$DOCKER_IMAGE'",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 80
              }
            ]
          }' > Dockerrun.aws.json

          # Deploy to Elastic Beanstalk
          eb deploy
