name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          # Install AWS Elastic Beanstalk CLI
          pip install awsebcli --upgrade

          # Initialize Elastic Beanstalk CLI
          eb init -p python-3.7 ${{ secrets.EB_APPLICATION_NAME }} --region ${{ secrets.AWS_REGION }}

          # Deploy to Elastic Beanstalk
          eb deploy ${{ secrets.EB_ENVIRONMENT_NAME }}
